vich_uploader:
    db_driver: orm
    metadata:
        type: attribute    # or attribute

    mappings:
        books_images:
            uri_prefix: '%books_images%'
            upload_destination: '%kernel.project_dir%/public%books_images%'
